/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './test.comp';
const styles_TestComponent:any[] = ([] as any[]);
export const RenderType_TestComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TestComponent,
  data: {}
}
);
export function View_TestComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[(l()(),import0.ɵted((null as any),['it"s works!']))],(null as any),(null as any));
}
function View_TestComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'testcomp',([] as any[]),(null as any),(null as any),(null as any),View_TestComponent_0,RenderType_TestComponent)),
    import0.ɵdid(57344,(null as any),0,import1.TestComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const TestComponentNgFactory:import0.ComponentFactory<import1.TestComponent> = import0.ɵccf('testcomp',import1.TestComponent,View_TestComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd3d3L3dlYnNpdGV3b3Jrcy9jcmFmdHV0aWxpdHkvc3JjL2NhdC90ZXN0Y29tcC90ZXN0LmNvbXAubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd3d3L3dlYnNpdGV3b3Jrcy9jcmFmdHV0aWxpdHkvc3JjL2NhdC90ZXN0Y29tcC90ZXN0LmNvbXAudHMiLCJuZzovLy9DOi93d3cvd2Vic2l0ZXdvcmtzL2NyYWZ0dXRpbGl0eS9zcmMvY2F0L3Rlc3Rjb21wL3Rlc3QuY29tcC50cy5UZXN0Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi93d3cvd2Vic2l0ZXdvcmtzL2NyYWZ0dXRpbGl0eS9zcmMvY2F0L3Rlc3Rjb21wL3Rlc3QuY29tcC50cy5UZXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiaXRcInMgd29ya3MhIiwiPHRlc3Rjb21wPjwvdGVzdGNvbXA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lCQ0FBOzs7O0lDQUE7Z0JBQUE7OztJQUFBOzs7In0=
